name: "Python CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@main

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@4f92594a5a1fd892119b68f9f530180f8196b1f4

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.10", "3.11" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@main
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
