name: "Python - Publish to PyPI"

on:
  release:
    types: [released]


permissions:
  id-token: write

jobs:
  publish:
    uses: darbiadev/.github/.github/workflows/python-pypi-publish.yaml@main
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
